changelog:
  exclude:
    labels:
      - ignore-for-release
    categories:
      - title: new fetures
        labels:
          - enhancement
      - title: bug fixes and improvements
        labels:
          - bug-fix
      - title: documentation
        labels:
          - documentation