name: Bug report
description: Report a reproducible bug or issue.
title: "[BUG] "
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following details to help us address the issue.
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Provide a short summary of the bug.
      placeholder: "Bug title"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug in detail, including steps to reproduce, expected behavior, and actual behavior.
      placeholder: "Steps to reproduce, expected behavior, actual behavior, etc."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the issue.
      placeholder: "1. Go to...\n2. Click on...\n3. See error"
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "What should happen instead?"
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: "What happened instead?"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Specify the environment where the bug occurred (e.g., OS, browser, version).
      placeholder: "e.g., Windows 10, Chrome 90"
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots about the problem here.
      placeholder: "Additional information or references."